//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hulom_ClientLoan_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanID { get; set; }
        public int ClientID { get; set; }
        public decimal LoanAmount { get; set; }
        public decimal Interest { get; set; }
        public int NoOfPayments { get; set; }
        public string PaymentTerm { get; set; }
        public decimal Deduction { get; set; }
        public decimal InterestedAmount { get; set; }
        public decimal ReceivableAmount { get; set; }
        public decimal TotalPayable { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Status { get; set; }
    }
}
