//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hulom_ClientLoan_System.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ID { get; set; }
        public int LoanID { get; set; }
        public int ClientID { get; set; }
        public decimal Collectables { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    }
}
